### ISSUE TITLE
Add an adaptative regulation in over climate mode

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#129]
Following a discussion in https://github.com/jmcollin78/versatile_thermostat/issues/125 issue, we need a regulation for over climate mode. This regulation should:
1. take care of temperature sensor in the room,
2. adapt the target temperature by adding / substracing a value if the temp room is under / over the target temperature.

So regulation can be done by VTherm using the target temperature value and adapting it constently.

Some PI (proportionnel-intégral) algorithm seems to be exactly what is needed for this.

**Comment by maia** [comment]
Thanks. I suggest a development in two phases:
1. Add a configuration option for a constant offset value: `underlying target temp = vtherm temp + offset`. This allows to adjust for differences between the temperature measured internally by the TRV and the room temperature, preventing a constant over- or underheating. For example, my living room is overheated by 1,0°C on average, so I would set the offset at 1°C, so when I set the VTherm target temp to 21°, the TRV is sent a target temp of 20°C and as it's wrongly calibrated it will heat the room to 21°C.
2. Develop an algorithm (e.g. based on bayesian time series models, regression,…) that constantly compare the sensor data to adjust the offset explained above.

The second phase is most likely much more work (and might not be ready for this winter?)

**Comment by jmcollin78** [comment]
Yep. Will see that.

**Comment by Ra72xx** [comment]
If you add some kind of own mechanism to control the way the  thermostat tries to reach target temperature, could you please nevertheless retain the current mode in which the thermostat does this with its own algorithms? 
In fact, this is the main reason I prefer VT over Better Thermostat: VT currently does not mess with the internal algorithms of the thermostat but assumes that the thermostat knows best what regulations have to be done to reach the target temperature to which it is set and which is also visible and controllable on the hardware.

**Comment by maia** [comment]
In my understanding this feature would only calculate a long term (days, weeks) offset between target temp and room temp and allow to adjust for that by sending the TRV a slightly lower/higher target temp. But of course it should not change the way how a TRV achieves the goal of a certain target temperature.

**Comment by jmcollin78** [comment]
That is what I intend to do @Ra72xx.

**Comment by jebeke65** [comment]
This might also solve my issue. I have a innova 2.0, used as AC heater. The temperature sensor is very inaccurate as it's withing the heater and can't be moved outside.
If you set the target temp e.g. to 24deg then it quite soon stops heating as the internal temp sensor reaches 24deg, although the temp sensor that gives the real temp, is only showin e.g. 20deg. As long as the wanted temp is not reached on the temp sensor, it should keep heating by e.g. increasing the target temp to "internal temp sensor + x", where the x is driven by how fast you want to have it increased. As the innova 2.0 is driven by a heat pump, this might take some time. There is also an internal resistor/heater that is switched on if the difference between the targettemp and the internal temp sensor is too big. If you have time enough to wait (no boost needed), then one can gradually increase the room temp. 

Would like to be able to control this behaviour on top of the underlying thermostat (here the innova 2.0) and I think this component is already doing a great thing.

**Comment by jmcollin78** [comment]
Development is starting.
What I intend to do is the following:
1. add an option to enable auto-regulation with 3 modes: light, medium, strong,
2. each option will have a set of parameter which will have influence on the algorithm: offset max, kp, ki
3. the algorithm is a PI (Proportional and Integral) which is a cycle based algorithm that is based on this method:
```

def ajuster_consigne(self, temperature_interieure, temperature_exterieure):
        """ Calculate a new consigne given some temperature"""
        # Calculer l'erreur (différence entre la température cible et la température intérieure)
        erreur = self.consigne - temperature_interieure

        # Intégration de l'erreur
        self.erreur_accumulee += erreur

        # Limiter l'erreur accumulée
        self.erreur_accumulee = min(self.limite_erreur_accumulee, max(-self.limite_erreur_accumulee, self.erreur_accumulee))

        # Calcul de l'ajustement (proportionnel + intégral)
        ajustement = self.kp * erreur + self.ki * self.erreur_accumulee

        # Limiter l'ajustement
        ajustement = min(self.offset_max, max(-self.offset_max, ajustement))

        print(f"Erreur: {erreur} erreur_accumulee: {self.erreur_accumulee}, ajustement: {ajustement}")

        # Si la température est proche de la consigne, réinitialiser l'erreur accumulée
        if abs(erreur) < self.seuil_stabilisation:
            print("Stabilisation")
            self.erreur_accumulee = 0

        return self.consigne + ajustement
```        
  It calculates an offset (ajustement in French) which is the combinaison of  the error (P) and the integral of the error (I).
  
 4. at each cycle, I will calculate the target (consigne in French) + offset, store this into a new `auto_regulated_target_temperature` and send this new target to the underlying device.
 5. Depending on the auto-regulation mode, the 4 parameters will have default values:
```
        self.kp = kp  # Gain proportionnel
        self.ki = ki  # Gain intégral
        self.offset_max = offset_max. # The max offset allowed
        self.seuil_stabilisation = seuil_stabilisation # The stabilization threshold 
```   
6. I keep all current attributes like target_temperature (not auto-regulated)


Any comments on the plan would be greatly appreciated if any !.

**Comment by maia** [comment]
Thanks a lot for working on it. I can't yet understand the code as I don't speak french and will need to get google translate to translate your code (isn't there a ChatGPT kinda tool that allows code translation? I would hope so). But I'd appreciate it if I could also define a manual offset that is not adjusted at all. And by the way, the outdoor temperature most likely has a strong influence on the offset. The colder it is outside, the higher the difference between the temperature measured at the radiator and the temperature measured in the middle of the room.

**Comment by jmcollin78** [comment]
> What is a "cycle"? Is a cycle something that happens every few minutes or hours or days?

yes.

I will translate the algorithm now and post it with English variables names.

**Comment by maia** [comment]
Haha, so is a cycle minutes, hours or days? :)

**Comment by jmcollin78** [comment]
Yes in minutes. All VTherm have a cycle in minutes configured.

The algorithm is English have been posted above.

**Comment by maia** [comment]
> Yes in minutes. All VTherm have a cycle in minutes configured.

Thanks, I will have to take a look what happenes within a single cycle. I think I remember having seen the cycle length in the config options but though it was not relevant for the "over climate" mode.

> It would add another layer of complexity. if the regulation works well, you don't need any manual offset. For now I do not intend to implement this.

Okay, I understand. And as for my personal experience with the needed offset: last winter it ranged from -1,0° C to +2,0° C, meaning that:
- On very sunny days with an outside temperature of not less than 12° C the target temperature at the valves could be set to 1°C less than the room temperature.
- On very windy days with an outside temperature of less than 0° C the target temperature at the valves had to be 2° C *above* the room temperature.

I only had to adjust the offset temperature about once every few weeks for a temperature that was "good enough".

**Comment by adi90x** [comment]
Hello,

This kind of regulation PI or (even PID) could also be use as an algorithm for an over_switch vtherm and help stabilize temperature targeted no ?

**Comment by jmcollin78** [comment]
> Hello,
> 
> This kind of regulation PI or (even PID) could also be use as an algorithm for an over_switch vtherm and help stabilize temperature targeted no ?

 VTherm over switch and over valve are already controller by an algorithm which is a TPI (Proportional and Integral). So we don't need to adapt the target temperature in that cases but eventually to adapt the coefs for the TPI algorithm.
 
 The auto-regulation (or regulation by changing the target temperature), only make sens when regulation is not done by VTherm itself.

**Comment by adi90x** [comment]
OK ```internal_temp``` is the temp of the TRV, right ?
But the error accumulated process could improve all vtherm precision, as of now vtherm will define heating as tpi_int*temp_int + tpi_ext*temp_ext, using your new algo when can have target_temp=tpi_int*temp_int+tpi_ext*temp_ext+tpi_offset*offset(compute by the algo) this may 1/ give à solution to get ride of external sensor 2/Help/Automatize tuning of the vtherm  3/ Improve the stability, even when external event modify temperature ( such as an open door) 
If implemented, it shouldn't be too difficult to make it available for all kind of vtherm no ?

**Comment by jmcollin78** [comment]
I understand your point but this is not TPI algorithm. TPI doesn't change the target temperature but changes the power percent. In the VTherm over switch configuration, you can choose an algorithm and the only choice now is TPI.

This is another algorithm like PID which is not planned to be implemented yet. But it will be one day, I hope so.
See https://github.com/jmcollin78/versatile_thermostat/issues/8 for real PID algorithms.

**Comment by adi90x** [comment]
Got your point, but if we use this algo with internal_temp = current temp it should work out of the box no ?  at least you can get ride of the external probe sensor ( + I am quite sure the proportinal/integral on error should be smoother than the TPI algo)

**Comment by jmcollin78** [comment]
@maia , @adi90x I have published an alpha release https://github.com/jmcollin78/versatile_thermostat/releases/tag/3.8.0.alpha1 if you want to test. i will do my-self in // on my AC device.

It is only for VTherm over climate for now.

**Comment by jmcollin78** [comment]
it is working in my house. you can test if you want.

**Comment by maia** [comment]
Thanks, I will test it as soon as possible (within the next 24-48 hours). Shall In enable debug/info/… mode in logging to track what it does? Is there anything else I could adjust or specifically test? Any specific kind of feedback you're looking for?

**Comment by jmcollin78** [comment]
I will change my regulation parameters that are a little too strong. So I will publish a beta1 in the next minutes.

Log in INFO should be enough.

I'm looking for regulation curve with the new `regulated_target_temp`, `current_temp`and `target_temperature` and hvac_action in the same graph. This should look like this and show the correct regulation:
![Capture d’écran 2023-10-30 à 17 40 54](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/38e7e0a6-234c-4672-b3fb-cbd5e8b2bac6)


You just have to put your thermostat into the "historic dahsboard": 
![Capture d’écran 2023-10-30 à 17 41 58](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/3d09212e-ac00-4b7f-8b23-c2ddf186ef76)

![Capture d’écran 2023-10-30 à 17 42 29](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/5340702e-fa19-49ed-b40d-0932c89b23bc)

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/3.8.0.beta1

**Comment by jmcollin78** [comment]
Huummm, ok thanks for the informations.

I don't understand why the temperature don't goes up even if the valve is open at 45% ? Is it normal ?
To stabilize the system need the temperature to increase when valve is open. When stabilization is done, command to the valve should be rare (only when something change)

Another remark, can you control directly the valve position of your EVE TRV ? If yes, I add a new VTherm over valve for doing need.

**Comment by maia** [comment]
This is completely normal. The cycle of a central gas heater works the following way:
1. The heater gets a request to heat (frequently: by a room thermostat in a single room).
2. It turns on the pump and turns on the flame at the lowest level (in my case at 5kWh gas consumption), the water is slowly heated to maybe 40°C while being pumped around the house for a minute or two.
3. If the thermostat turns off the heating request, the cycle is over. Otherwise the flame is slowly adjusted (in my case up to 25kWh) over the next minutes, the cycling water temperature slowly increases to up to 60°C (or 55 or 70, depending on the setup).
4. Once the temperature of the water returning to the central heater is too high (e.g. because most TRV valves are closed), the flame is turned off. The pump stays on for 3-10 minutes. In that case the gas heater will stay off for 10-60 minutes (depending on the setup), no matter if there is a new heating request.
5. Ideally, the returned water isn't too hot and the radiators heat the rooms. The thermostat turns off the heater. The pump stays on for a few more minutes.
6. Only when the room temperature of the thermostat drops by at least 0,5°C, a new cycle begins. This can take a long time too.

In my current case, the gas heater was simply off for 20 minutes, as in the previous cycle the water returned was too hot. This is common when the outdoor temp isn't very cold and the gas heater is a bit larger than necessary. The goal is to prevent frequent cycles. A gas heater shouldn't run more than 4-6 cycles per hour.

As the the room I'm testing in at the moment: The radiator now is warm, as it has water with ~45° temperature in it. It will take another 30-60 minutes until the room temperature rises significantly. So between the start of the adjustment of VTherm and reaching the target temperature it'll take about 2 hours.

Of course I could adjust my gas heater and tell it to heat the water to 70°C and to turn on up to 20 times per hour, but this is a waste of energy. Even the water pump for the radiators needs lots of energy, not even considering the gas. That's why it's only turning on a few minutes per hour.

**Comment by maia** [comment]
PS: no, I cannot control the valve directly. Homekit devices do not expose this. There will be a Matter upgrade for my Eve Thermo TRVs in mid-November, then the valve might be adjustable, I don't know yet. But Eve does a pretty good job at adjusting the valve.

**Comment by maia** [comment]
PPS: Within the last hour, VTherm changed the regulated temperature about 20 times. That's 1/500th of the entire lifespan of the TRV.

**Comment by jmcollin78** [comment]
Ok. You can set the regulation mode to None.

**Comment by maia** [comment]
> Ok. You can set the regulation mode to None. 

I've now changed from "medium" to "light", that might reduce the number of changes.

And I'm fine with having a single thermostat that's at the end of its lifespan soon due to beta testing. It's just not production ready yet with so frequent updates.

**Comment by jmcollin78** [comment]
FYI, here a great regulation done by the algorithm:

![Capture d’écran 2023-10-30 à 23 38 45](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/067ce708-3ea8-417d-8cb6-5445fe50c62a)

**Comment by adi90x** [comment]
Will also try to use it over another vtherm to have proof of interest 😁

**Comment by jmcollin78** [comment]
@maia for your case, with a central gas heater and a very low heating cycle, I will add two parameters to the algorithm:
```
"auto_regulation_dtemp": "The threshold in ° under which the temperature change will not be send", -> default value of 0.5
"auto_regulation_periode_min": "Duration in minutes between two regulation update".    -> default value of 5 min. In your case, you should put something like 1 hour to see if the regulation occurs.
```

I already add a service which you can call to change the auto_regulatio_mode without having to reconfigure the VTherm.

This should be quick to implement. I let you know when it is available.

**Comment by maia** [comment]
@jmcollin78 Being able to adjust the step size (the thermostat only accepts 21.0°C, 21.5°C, 22.0°C, 22.5°C, 23.0°C,…) and the cycle duration should help. I'm looking forward to the next beta.

**Comment by jmcollin78** [comment]
Hello @maia  and @adi90x ,

The new beta is here: https://github.com/jmcollin78/versatile_thermostat/releases/tag/3.8.0.beta2
Have a look to the release note please.

**Comment by maia** [comment]
I'm now using the "medium" setting in six rooms, with 0,5°C step size and a 15min cycle. As it's quite warm outside, the heater isn't on a lot, so some rooms stay warm even without heating, others stay too cool. But I did notice something that looks like a bug:

<img width="367" alt="Bildschirmfoto 2023-10-31 um 18 15 26" src="https://github.com/jmcollin78/versatile_thermostat/assets/9836/46471522-c614-405e-9693-8fd13ec0b031">

At 18:00, the preset for this room switched from "eco" to "comfort", raising the target temperature from 20°C to 21°C. VTherm had reduced the regulated temperature to 18,5°C, as it was too warm in the room. At 18:00 the target temp increased by 1°C, to slightly above the current room temperature. But the regulated temperature went from (target-1,5) to (target+1,5). This cannot be correct. Why should the offset jump by 3°C, if the target only changes by 1°C?

**Comment by maia** [comment]
I've been using the "medium" mode in six rooms for the past hours. It's warm outside, so the heater doesn't turn on a lot, so the temp in the rooms doesn't change a lot.

I've noticed a bug:

<img width="367" alt="Bildschirmfoto 2023-10-31 um 18 15 26" src="https://github.com/jmcollin78/versatile_thermostat/assets/9836/b8920b44-00a3-498c-9cfe-963fb49e60f8">

The calculated offset (regulated_temp - target_temp) should not change when the preset changes. Once the algo finds a "good" offset that is added/subtracted from the target temperature to ensure a proper room heating, it shoulnt not be "reset" when a preset changes the target temperature.

The above is an example for something going wrong: Around 17:00 the algo thinks that the offset can be -1,5° from the target temperature at the valve. But then at 18:00 the target temperature is raised by 1°C and the offset increases by 3°C, instead of staying at -1,5°. 

@jmcollin78 Maybe you have something in mind that's fine for electric heaters but not for valves? What I've been suggesting over the past week or so is a stable offset value that can be defined which will always be added/subtracted from the target value and which is then passed to the underlying. So if a room heats fine with an offset of 1°C, then that's what is added to the target temp for the next weeks (until the outdoor temperature changes radically). But what the algo currently tries to do is to outsmart the valves by adjusting the target temperature over minutes or hours – and resetting everything when the target temp is changed.

I'd be most happy if there was an input field in calculation named "offset" where I could define "+1,5°C" which is then used for the next weeks, when I notice a room is warmer than intended. And I'd be even more happy if that offset could be a function of the outdoor temperature (lower offset at lower outdoor temperature). The current algo seems to have a different goal?

**Comment by jmcollin78** [comment]
Are you in beta3 ?
I reduce the coefficient in beta3, for Medium and Strong regulation mode because it was really too much.

+3 ° is the max allowed for Medium regulation so it is not totally anormal. I will do the calculation by hand to see if something weird happens.

Moreover, I don't understand why it was heating at 16h45 with a regulated temp at 18,5° and target at 20°. There is something wrong at this place.

**Comment by maia** [comment]
> Are you in beta3 ? I reduce the coefficient in beta3, for Medium and Strong regulation mode because it was really too much.

Yes, I'm in beta3.

> Moreover, I don't understand why it was heating at 16h45 with a regulated temp at 18,5° and target at 20°. There is something wrong at this place.

I don't know when it will shade the area orange. How does it define "heating"? Is it orange when the valve opening is above 20% or so? I couldn't figure out the orange shading, so I currently am ignoring the color.

**Comment by jmcollin78** [comment]
> Why is it above the target temp around 14:00? Why does it jump around 18:30?

It would like to have the log around 18:30 ? Did you restart HA ? Or the integration or change the configuration of the VTherm (which reset all parameters) ?

**Comment by maia** [comment]
> It would like to have the log around 18:30 ? Did you restart HA ? Or the integration or change the configuration of the VTherm (which reset all parameters) ?

I just realised I had the log level set to warning, I'm sorry. I now changed it to info and restarted HA. But I didn't do anything around that time, I was eating dinner.

Here's the valve graph for the same room added below. You can see that Eve Thermo TRVs are doing a good job at keeping a temperature constant. Their marketing material talks about "AI", but whatever it is, the valve is rarely at 0% or 100% and it holds the room temp steady with small changes. The only issue is that many TRVs in HA do not allow access to the offset variable. Which is why I suggested to add an offset variable in VTherm that is more or less constant and does not change every few hours:
<img width="1205" alt="Bildschirmfoto 2023-10-31 um 19 16 45" src="https://github.com/jmcollin78/versatile_thermostat/assets/9836/bf424cc7-0bdb-4073-a819-e32c35a5de64">

**Comment by jmcollin78** [comment]
I have a regulation running all the afternoon and I don't experience this. I'm with a reversible climate. It was too warm so I force the temperature to 22° at 11h00. I've got the +3° when I change the target.

![Capture d’écran 2023-10-31 à 19 14 06](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/247212a1-cf13-46d6-93af-9fe4aced0eb1)

As you said, when the target change, I reset the accumulated error which no more valuable in my opinion because conditions changes. But may be I'm wrong and I should keep the error.

Let's do the calculation by hand:
The accumulated error is limited to 25 which is then multiply by 0.08 (= +2 °).
The error should be near 0,3 which is then multiply by 0,4 (= 0,12).
The 3rd factor is the external temp: (target_temp - external_temp) * 0,1 (= 10 * 0.1 = 1)

So the offset is +2 + 0,12 + 1 -> 3,12° limited to 3°. So the calculation seems good. This shows that accumulated_error is NOT resetted else we should have +1,12 ° . Maybe the bug is here.

**Comment by maia** [comment]
> As you said, when the target change, I reset the accumulated error which no more valuable in my opinion because conditions changes. But may be I'm wrong and I should keep the error.

Yes, you should keep the offset/error. Two examples:
1. Imagine a kitchen. 3x a day food is prepped. The oven is on. Children are playing. Grown ups are cooking food. Even if the temperature measured at the TRV below the window is 21°, the room temperature is higher, let's say 23°C, because people and oven,… heat the room. In that case the offset in the kitchen will be a (more or less) constant -2,0°C.
2. Imagine a room with windows on one side with a radiator below, and a door on the other side of the room. This door leads to the outdoor area. The door is opened frequently every day, causing the room temperature to be lower than the temperature measured at the TRV. The offset would probably be at +1°C.

And unless the usage of the rooms change, it doesn't matter if the target temperature is set to 20°, 21° or 22°. The room no. 1 will always be warmer than intended, the room no. 2 will always be cooler.

Only if the outdoor temperature changes radically, the offsets change. Imagine it has -10°C outdoors. Now the offset in the room number two will need to rise to +3°C to ensure that the room temperature is okay, even if the door is opened frequently.

**Comment by jmcollin78** [comment]
I will try to remove the reset indeed. I think you are right.

**Comment by maia** [comment]
> I will try to remove the reset indeed. I think you are right.

Great. Also the offset should survive HA restarts. Something that might need a day or two to settle properly should not be reset unless the user wants to reset it manually.

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/3.8.0.beta4

I remove the reset at each target temperature change and I lower all coefs. There were still too much.

> Also the offset should survive HA restarts

This makes no sense. The offset is fully calculated at each cycle and change. This offset is not stronger because it has been calculated during 3 days. The eventual restored value will not be used and recalculated immediatly.

**Comment by maia** [comment]
I installed beta4 at 4:45 in the morning. The algo currently "overshoots" with its swings in both directions, as it doesn't consider that heating a room by 1°C will take 1-2 hours. 

How can I tune the variables to prevent that behaviour? I'm currently using "medium", 0,5°C step size and a 15min cycle.

![IMG_5918](https://github.com/jmcollin78/versatile_thermostat/assets/9836/758ecf28-950e-4c33-9aee-ff4b28a3ea0a)

**Comment by maia** [comment]
Maybe I should set the minimum cycle to 24 hours to prevent the issues of overshooting when the preset changes during the day?

**Comment by maia** [comment]
> This makes no sense. The offset is fully calculated at each cycle and change. This offset is not stronger because it has been calculated during 3 days. The eventual restored value will not be used and recalculated immediatly.

Recalculation needs a few cycles. So with a cycle of 15min this might mean 1-2 hours until it's recalculated. With a cycle of 24 hours (as mentioned above) it would mean 3-4 days lost with a single HA reboot.

**Comment by jmcollin78** [comment]
In your case, I would recommend the Light mode of the regulation algorithm and a period of 30 min because your heating is slow. You definitively don't need much regulation thanks to "the good jobs" of EVE valves.

Note: I will release in few minutes.

**Comment by jmcollin78** [comment]
I will close this discussion, but you can continue if you want to post your experience / remarks / trouble here.

**Comment by jmcollin78** [comment]
> By the way, how does the regulation algorithm deal with open windows? Will it be paused for the time the window is open (e.g. 20 minutes) or will it steadily increase the regulated target temp?

When the window is open, the VTherm is shut off. Then then temp will go down and the offset be at its maximum. When the window is closed, the VTherm turns on and send the maximum regulation to underlying this will boost the heating of the room. And progressivly the offset will recover the stable value.

I guess this is expected behaviour and the big advantage to have an offset which is depending of the conditions.

**Comment by maia** [comment]
> When the window is closed, the VTherm turns on and send the maximum regulation to underlying this will boost the heating of the room.

It very much depends on the construction and outdoor temperature if this is helpful or not. Because one could also argue the other direction: When a room that was constantly at 20°C is filled with cold air for 30 minutes and it's air temperature drops to 17°C, this does not mean it needs to be heated at all. As all walls, the floor and the ceiling all still have 20°C and hold temperature much longer than air, the room might be back to 20°C within another 30 minutes even with *no* heating at all.

In situations with bad construction that does not maintain temperature long and with very low temperature outdoor it's different.

But think of a big church and how it can hold its temperature over months. It all depends on the mass of stone/concrete/… you're surrounded with.

Also it seems you don't trust how TRVs regulate the valve and try to boost its regulation. This is a completely different use case than what I was describing in the past 2 weeks: `current_offset = long_term_difference_of_target_temp_and_room_temp + (target_temp - outdoor_temp) * factor`, where `factor` would be about 0.05 in my specific case.

**Comment by adi90x** [comment]
Hello, 

Instead of using 3 different classes ( or even 4 in code ) why don't we have only one```RegulationParamXXX`` and let user input all parameters in setup ? ( Same one service can be use to update all those parameters ) and then maybe only put some basic parameters in the documentation ? 
```
    kp:float = 0.6
    ki:float = 0.1
    k_ext:float = 0.2
    offset_max:float = 4
    stabilization_threshold:float = 0.1
    accumulated_error_threshold:float = 30
```

**Comment by jmcollin78** [comment]
> Instead of using 3 different classes ( or even 4 in code ) why don't we have only one```RegulationParamXXX`` and let user input all parameters in setup ? ( Same one service can be use to update all those parameters ) and then maybe only put some basic parameters in the documentation ?

Because it makes 6 different parameters + 2 parameters (dtemp and period) to input which is very much complicated.
Let see if those values make the trick.

**Comment by adi90x** [comment]
> > Instead of using 3 different classes ( or even 4 in code ) why don't we have only one```RegulationParamXXX`` and let user input all parameters in setup ? ( Same one service can be use to update all those parameters ) and then maybe only put some basic parameters in the documentation ?
> 
> Because it makes 6 different parameters + 2 parameters (dtemp and period) to input which is very much complicated. Let see if those values make the trick.

Maybe it could be a new page in config when regulation is ticked no ?

**Comment by jmcollin78** [comment]
I thought about it but, really i want to keep it as simplier as possible. I'm pretty sure the parameters given will satisfied 99% of the needs.

There is already 60 parameters now, and it is very important to keep that as simplier as possible for most of the users. I see some PID algorithm and other AI algorithms with lot a confusing parameters and many people having great difficulties to use it. That is not my philosophy.

But what is possible, is to have an "expert mode" in the Switch type page, and then a new page or a config in configuration.yaml. So that expert people will be able to specify their parameters. In that expert mode, it should be possible to specify a static value as asked by @maia . 

But for now, because, I do a lot of work on the last month, I will make a pause and wait for user feedbacks on the current new self-regulation.

Feel free to propose a PR in the mindset exposed above if you think you can do it and have time for this. I would be please to merge it.

**Comment by jmcollin78** [comment]
I add a Discussion section on the root page of Versatile Thermostat if you want to continue this discussion

**Comment by ThomasCr** [comment]
Hi, I have some questions:
- if PID mode in the current release already active/present?
- if yes
- is it used when I select tpi algo?
- dos the time on 5 min mean it switch on for 5 min and off again? This looks not like a PI / PID controller...?
