### ISSUE TITLE
"Set Auto Regulation" mode didn't affect "activity" preset

### ISSUE THREAD

**Issue by DrDimedrol** [jmcollin78/versatile_thermostat#190]
Hi, thank you for great thermostat!

In my config I have motion detection via motion sensors. When I have "activity" preset active using Scheduler and try to set temperature "Call a service 'Versatile Thermostat configuration: Set temperature preset' " to "eco" and "confort" , it didn't affect to "activity" preset. I need to change preset to some other preset and return back to "activity" preset to get correct temperature.

**Comment by jmcollin78** [comment]
Hello @DrDimedrol,

You are right. The activity preset doesn't have a temperature preset but uses the Eco or Comfort one when it switch. Once switched, changing the temperature of the preset will not affect the current target temperature.

Personnaly, i'm not totally sure it is a good idea, because the preset Eco is NOT selected by activity. Only its temperature is used.

Have you tried changing the Activity preset with the service ? When I look at the code, it seems possible that it will works. Or I can surely make it possible to work, if not.

**Comment by DrDimedrol** [comment]
> Have you tried changing the Activity preset with the service ?

Service allow change temperature only for presets "eco", "confort" and "boost". 
And it will be good to have also Services to turn ON and Off thermostat and Service to change preset.

**Comment by jmcollin78** [comment]
This already exists on the climate level.
