### ISSUE TITLE
Expand Motion Feature to Include Other Entities like Plugs, Lights, etc.

### ISSUE THREAD

**Issue by syberx** [jmcollin78/versatile_thermostat#224]
It would be nice if you couldn't select motion detectors with the Motion. So other sensors, plugs, lights...

**Comment by jmcollin78** [comment]
Not understood sorry

**Comment by syberx** [comment]
on the "motion" i can only add "Motion sensor " i can not use a light. I recognize my presence in the room when the lights are on.

**Comment by jmcollin78** [comment]
Ah ok. I wil not do that, because using a light will really not act as a motion sensor. A motion sensor is up for lat say 30 sec and the turns off. It never stays up for a long time.

You can always have a virtual motion sensor which is based on the light status if you want.

I cannot add everybody ultra specific features on the VTherm, you have to understand this.
