### ISSUE TITLE
[5.0.0] - Unable to set "window open" settings values

### ISSUE THREAD

**Issue by MaxWaldorf** [jmcollin78/versatile_thermostat#280]
The windows open detection windows to enter values, keeps on coming up and doesn't validate...

**Comment by WarC0zes** [comment]
Hi,
Yes, I've this error in the log. We cannot finalize a configuration.
```
2023-12-18 08:02:24.683 ERROR (MainThread) [custom_components.versatile_thermostat.config_flow] Only one window detection method should be used. Use window_sensor or auto window open detection but not both
```

**Comment by jmcollin78** [comment]
Hello, hum I see the problem.

You should uncheck the "Use central configuration" for the window and remove the values for auto window detection.
I will improve this but it should be working with that

**Comment by WarC0zes** [comment]
> Hello, hum I see the problem.
> 
> You should uncheck the "Use central configuration" for the window and remove the values for auto window detection. I will improve this but it should be working with that

if we delete the values of the auto detection window and validate. This resets the default values and we cannot continue to finalize the configuration.

**Comment by jmcollin78** [comment]
I wonder why I don't run into this case. I will certainly not be able to fix today.

**Comment by jmcollin78** [comment]
I try on my side.
On the "Central configuration" I've got this:

![Capture d’écran 2023-12-18 à 10 14 15](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/8cfe9190-ee87-4459-a566-9dd140c66e19)

In the VTherm configuration itself, I've got this:
![Capture d’écran 2023-12-18 à 10 15 16](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/1694a3de-b149-47d5-a9ed-1284863922ab)

And this is working fine.


If I uncheck the "Use central configuration" :
![Capture d’écran 2023-12-18 à 10 16 35](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/569ab024-f49a-49d4-a371-cf04139eeba5)

I cannot validate this window because the both window mode are configured.
![Capture d’écran 2023-12-18 à 10 17 40](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/5ffa1d3a-b6d0-470e-9292-0e519f4afbdb)

The error is not displayed and that is the bug for me.

And you are right, when I remove the auto detection open window parameters:
![Capture d’écran 2023-12-18 à 10 18 51](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/d262ff9a-6472-4dff-9ac7-4fab0ba97b55)

The error is still there (but not displayed).

So the workaround is to add a window sensor in the previous page and check "Use central configuration" or to deactivate "With window detection" in the first configuration page.

![Capture d’écran 2023-12-18 à 10 21 12](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/951afa46-5fa1-4be3-b2a0-4801f69da925)

**Comment by WarC0zes** [comment]
I used the central configuration and I was able to finalize the Vtherm configuration.
But you have seen that if we do not use the central configuration for the openings, we cannot finalize the configuration.

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/5.0.1
