### ISSUE TITLE
Add schedule preset

### ISSUE THREAD

**Issue by mycanaletto** [jmcollin78/versatile_thermostat#283]
Hello,

This thermostat is certainly the most advanced available for Home Assistant.

As with the others, scheduling is not integrated, and I can understand Jean-Marc's decision not to integrate this part, given the complexity of the task. There are several ways of scheduling, either via integration or in yaml, which is what I do.

Some scheduling methods check the various parameters every 5/10 minutes and restart the current schedule.

In order to prevent the VT from reverting to the current schedule after 10 minutes, I check the VT state to see if the `boost` preset is activated (`preset_mode`) and this allows me to set a constraint on my schedule.

It's quite easy, and with the `saved_preset_mode` attribute it works even if I've manually changed the setpoint.

However, if I manually change the setpoint, the preset returns to `none` and I can't use the `none` preset to inform my schedule that I'm returning to scheduled mode immediately.

That's why I'd like to add a `schedule` preset that would do nothing other than be announced in the VT state (or an event, but it's the same thing).

I'd already asked for this, but I may have misspoken.

**Comment by jmcollin78** [comment]
Hello @mycanaletto ,

Thank you for the compliments !

I clearly understand your point, but there are still two questions around this:
1. what the boost preset is doing here ? Why do you not have the same trouble with other presets ? (Comfort). Are you using the Boost preset as a temporay preset or something like that ? lI see your post here: https://www.canaletto.fr/post/home-assistant-timers-and-choose and that's why I'm asking this,
2. a preset is a pre-configured target temperature. No more than this. Having a preset which says "I'm in a scheduled mode" is really not a preset. 

Tell me if I'm wrong, but the need behind the "scheduled" preset is to:
1. temporary set the VTherm to Boost,
2. ignore the preset change by scheduler during a timed timeframe
3. at the end of a timer, re-set the preset to scheduled preset (which is maybe the previous one, just before switching to boost).

Am I right ?

**Comment by mycanaletto** [comment]
The boost preset I'm talking about is just one example. It could be comfort, eco or frost, or a setpoint change with + or -.

In my logic for the end-user of a planned thermostat, a preset is a manual choice (as opposed to what is planned). So I exit planned mode (which I pause thanks to the VT status) when the end user chooses a preset (or simply raises the setpoint).

What I'm looking for is to have a button next to none (which I've imagined could take the form of a preset) to allow the user to return to planning mode and thus exit preset mode. 

I know how to make the next iteration of my schedule override the preset, I can also do it via a timer, but I don't have on the card a way to resume scheduling with a click after a manual override (boost, eco, comfort or setpoint change).

Of course I can make a button on a stack card, but I'd find it more logical (cool) to have it on the card.

I reasoned visually, so I thought preset, but in logical mode it's more of a clickable flag identifiable in a state.

**Comment by jmcollin78** [comment]
> n my logic for the end-user of a planned thermostat, a preset is a manual choice

Ok that is the important part and this part is at the opposite of the VTherm philosophy. Presets are made to being called by the Scheduler and if the user wants a specific target temperature, he change the target temp and the VTherm goes into manual mode (no preset). With this method, at the next scheduler cycle, the VTherm will restore the scheduled mode automatically.

Is it an option to modify your scheduler mecanism and use the internal HA Scheduler ?

> I reasoned visually, so I thought preset, but in logical mode it's more of a clickable flag identifiable in a state.

Yes it could be but this is a very specific flag for your specific use case. I'm pretty sure that with the standard VT events we will have a solution. Each preset change is notified, may a notification when direct target temp change is missing.

Anyway, it is now more clear of what is expected and I will give it a though.

**Comment by Swiiney** [comment]
Hi, what could be great with schedule inside (or dedicated to) the VTherm would be to schedule the time I want to reach a temperature and not the time I want to change the preset.
With this the VTherm could be able to determine when to start heating to reach the correct temperature depending the house comportment, the current temperature, the heating capacity, the outside temp(, etc... if any)
A standard scheduler cannot manage this, maybe specific VTherm scheduler could since it could be aware of temperature information.

A use case exemple :
You want to reach 19°C at 18h. You program this in the scheduler.
According to previous days usage the VTherm "knows" when to start heating maybe 17h or 16h for cold days.
With this you avoid to start heating at 16h if the difference between the 18h preset and the current temp is limited ; and you avoid to wait in cold at 18h because the house current temp is very low.
(not sure to be clear, for better explanation this how Netatmo works in "anticipation de chauffe (Auto-Adapt)" mode)

Regards and thanks for your work

**Comment by mycanaletto** [comment]
> > n my logic for the end-user of a planned thermostat, a preset is a manual choice
> 
> Ok that is the important part and this part is at the opposite of the VTherm philosophy. Presets are made to being called by the Scheduler and if the user wants a specific target temperature, he change the target temp and the VTherm goes into manual mode (no preset). With this method, at the next scheduler cycle, the VTherm will restore the scheduled mode automatically.

In my planning (Scheduller or Yaml) I never call presets but a target temperature...

When I started with HA there was no preset on the climate generic. And with fine planning, you might as well call temperatures. 
Hence the fact that the presets would be used mainly for boosting. And when I do something, I like to offer all the possibilities (this is for my brother).

**Comment by jmcollin78** [comment]
Hello @mycanaletto ,

I'm sorry but I will not do that. This is too much specific for your way of working.
I will close this issue don't hesitate to reopen if you think I'm wrong.

**Comment by mycanaletto** [comment]
I understood...

Happy New Year ;-)

**Comment by jmcollin78** [comment]
Yes happy new year too
