### ISSUE TITLE
off button ignore when window open

### ISSUE THREAD

**Issue by jfchadeyron** [jmcollin78/versatile_thermostat#289]
With VTerm v 5.1.0, when i click on the off buttom during the windows open detection, VTerm will start heat when the window will be closed.

**Comment by jmcollin78** [comment]
Hello @jfchadeyron ,

If the window is open, the VTherm is off so clicking on off does nothing. Yes, and is that wrong ? Are you describing the expected behavior or the current behavior ?

Can please follow the issue template: have VTherm attributes (what kind of VTherm do you use), what is observed , what is expected, ... It helps me to find is something is wrong.

Thank you.

**Comment by jfchadeyron** [comment]
I want to turn off the heat even the window is open or close. It's not possible : we must wait window is close to turn off the heat.

**Comment by jmcollin78** [comment]
> I want to turn off the thermostat even the window is open or close

If the window is closed, I suppose there is no issue to turn off the VTherm. 
If the window is open, the VTherm is already off, so it cannot be turned off more than that.

> we must wait window is close to turn off the thermostat

Maybe what you want is that (and I would like you say it like that and not on a single sentence):
1. Initial state: VTherm is on and heating,
2. open the window. The VTherm turns off. That is ok,
3. click on turn off on the VTherm.  The VTherm stays off. That is ok,
4. close the window. Observed: the VTherm turns on, Expected: the VTherm stays off because the user intentionnaly turns off the VTherm.

If this is what you want, it is not so easy : 
1. the feature is: when window is closed, restore the state before turning off the VTherm,
2. when clicking on Off on an already Off VTherm there is no state change. So no notification I guess and I think I won't be able to do whatever. I'm not totally sure of that,
3. If I suppose it will be notified, I have to change the restored state and not the current state.

**Comment by jfchadeyron** [comment]
Thank you very much for this explain (and sorry for my english).
1- why you don't want to replace restored state by off if clicking on off ?
2- a proposition :  create a "suspend mode" when windows is open to see the difference between if a windows is open and if thermostat is off.

**Comment by jmcollin78** [comment]
I don't want to complexify more. I close the request.
