### ISSUE TITLE
expand central configuration

### ISSUE THREAD

**Issue by maia** [jmcollin78/versatile_thermostat#318]
I would like to suggest to move a few configuration aspects to the central configuration:
- cycle duration
- self-regulation dropdown
- regulation threshold
- regulation minimal period
- auto fan mode

And by the way, I'm really happy how the central configuration turned out, I think it's a big advantage. Thanks for developing it!

**Comment by jmcollin78** [comment]
Hello @maia ,

After considering this proposition it seems that:
1. cycle can be possible because it is in all vtherm type configuration. In my configuration, I use different cycle to "randomly" dispatch heating and avoid havind all`over_switch` heater starting at the same time. So that is why cycle is a "personal" VTherm configuration and not a central one. If you do not have aby `over_switch` VTherm i understand your need,
2. regulation parameter are not common to all VTherm type: once again, `over_switch` doesn't have this so It make no sens to put it in common. People that don't have any `over_climate` will not understand those parameters and think they have an influence on regulation.

So, I will reject this proposal for now but keep on suggesting enhancement please, you have done a great job for VTherm enhancement in the past.

**Comment by jmcollin78** [comment]
I understand your point but most of feature are multi-vtherm. And most of the work is now done. I just have to maintain, fix the bugs (threre is still !) and add some small missing features.

Having 3 integrations is more hardwork I think. I currenlty have 2 integration to maintains and it is very time consuming (and I have a "real" work in //).
