### ISSUE TITLE
2 Stage Heating

### ISSUE THREAD

**Issue by kadaan** [jmcollin78/versatile_thermostat#33]
**Is your feature request related to a problem? Please describe.**
I have a mini-split system that cannot keep the set temperature when heating if the outside temperature gets too low.  I have a pellet stove that is used as a backup heat source and as auxiliary heat.  

**Describe the solution you'd like**
I would like to be able to pick a second switch (in my case a Shelly 1 Plus) which controls an auxiliary heat source that is enabled/disabled when the primary heat source cannot keep the target temperature.  The trigger would be configurable with a combination of time and degrees from target temp (ie. if the current temperature is 2 degrees less than the set temp for 10 minutes).  The second heat source should have min/max on and off time configurable to prevent short cycling.

**Describe alternatives you've considered**
Currently with my SmartSi thermostats I have a separate NodeRed automation to handle this.

**Additional context**
None

**Comment by jmcollin78** [comment]
Hello @kadaan ,

Thank you for your report. There is already a feature called aux_heat in the standard simple thermostat but I have to admit I don't understand what it is related for.

I see some services like: [turn_aux_heat_on, def turn_aux_heat_off](https://www.home-assistant.io/integrations/climate/#service-climateset_aux_heat) which seems exactly to be what you need.

Because I implement all features of standard climate entity, I wonder if it is not working out of the box.

Can you try calling the SERVICE CLIMATE.SET_AUX_HEAT to see what happens ?

**Comment by kadaan** [comment]
I will try and see.

**Comment by jmcollin78** [comment]
Any news on this ?

**Comment by jmcollin78** [comment]
I close this due to non activity. Please reopen if needed
