### ISSUE TITLE
Fan Cycle

### ISSUE THREAD

**Issue by kadaan** [jmcollin78/versatile_thermostat#34]
**Is your feature request related to a problem? Please describe.**
I would like to control my SmartSi thermostats with the component.  My current thermostats have a Fan Cycle which allows you to have the fan run X minutes per hour, whether or not heating/cooling is needed.

**Describe the solution you'd like**
Versatile Thermostat should be able to be configured to run the fan for X minutes per hour.  Picking a runtime per hour in 5 minute increments from 0 - 60 would cover my use case.

**Describe alternatives you've considered**
I could run a separate automation, but that seems like it would conflict with this thermostat.

**Additional context**

**Comment by jmcollin78** [comment]
Hello @kadaan ,

If I understand well you want to extend your actual SmartSi thermostats with the feature of the Versatile Thermostat.

If yes, this is exactly why I implement the "Thermostat over climate" feature.
Instead of controlling a switch, you can control another underlying thermostat so that you will have window, preset, presence check, power mangement, ... etc.

This is in beta now and working on my environment (which is limited so I can't test all cases).
If you think this can be useful for you, I propose you to install the 2.0.0.beta (the last), configure a new VersatileThermostat over your existing one and test if it works.

If not don't hesitate to come back (it is a beta).

We this method, you don't have to touch your existing thermostat to test.

**Comment by kadaan** [comment]
Let me see if the beta accomplishes what I want.

**Comment by jmcollin78** [comment]
Any news on this ?

**Comment by jmcollin78** [comment]
I close this due to non activity. Please reopen if needed
