### ISSUE TITLE
Enhancing Security mode

### ISSUE THREAD

**Issue by adi90x** [jmcollin78/versatile_thermostat#42]
Hello,
Using latest version available, it seems that security mode does not start as expected.
I.e : temperature is not update since more than 2h ( setting I put) and security mode still didn't start, however outdoor temperature still update so maybe the security mode does not trigger due to that.
Climate entity below :

```
hvac_modes:
  - heat
  - 'off'
min_temp: 7
max_temp: 30
preset_modes:
  - none
  - eco
  - comfort
  - boost
current_temperature: 9.1
temperature: 8.5
hvac_action: idle
preset_mode: none
hvac_mode: heat
type: thermostat_over_switch
eco_temp: 14
boost_temp: 18
comfort_temp: 16
eco_away_temp: null
boost_away_temp: null
comfort_away_temp: null
power_temp: 7
ext_current_temperature: 1.3
current_power: 37
current_power_max: 6000
saved_preset_mode: none
saved_target_temp: 10
saved_hvac_mode: null
window_state: 'off'
motion_state: null
overpowering_state: false
presence_state: null
security_delay_min: 120
last_temperature_datetime: '2023-02-07T17:22:05.283082'
last_ext_temperature_datetime: '2023-02-07T21:49:05.812406'
security_state: false
minimal_activation_delay_sec: 60
last_update_datetime: '2023-02-07T21:49:05.820742'
underlying_switch: switch.chauffage_sdb
on_percent: 0
on_time_sec: 0
off_time_sec: 600
cycle_min: 10
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
friendly_name: Test Sdb Thermostat
supported_features: 17
```
Don't hesitate if you need more info !
Et en tout cas Bravo pour cette excellente implementation !

Bonne soirée,

**Comment by adi90x** [comment]
Ok I guess it is related to #30, but in that case maybe it could be good to document the 75% or even better to be able to set it at creation ?
Even better, in my case thermometer ( 9.1°)  is no longer responding with a 1.1 degres over set temperature ( 8° ), it would be better to have the thermostat in security mode to make sure I can have the information to either send an alert or do something else, like another action ( example : run heater for a set fixed (by user) duration) like 5min/hour ?

**Comment by jmcollin78** [comment]
Security mode is set when one of the both temperature is too old AND if the heater is heating (on_percent > 0.75).
I see you find it alone.

I will implement some notifications when a heater goes to security mode, I think this will help to be aware of what happens. I think it would be possible to add a notification when a temperature is not changing after the delay.

Yes, good idea.

You point 2/ I think is not so easy to do and I think not very useful 5 min/hour is certainly not enough to go from 7° to 8° and the value will depend of the temperature difference.

I retain the notification when temperature delay is expired: https://github.com/jmcollin78/versatile_thermostat/issues/43

I will close this one and only keep the #43

**Comment by adi90x** [comment]
Hello, 

Thanks for your answer, my second was very basic, instead of just keeping whatever % it was before going into security mode just applied a user defined percentage.
My post was a bit confused, but for example it seems better for me to let the user decide how much the heater should run when thermostat is not available instead of using last value.
My example was yesterday, temperature stop reporting when it was over target temperature , so control output was 0% and it would have remain like that for the whole night and room temperature would have been way too cold ! 
Maybe the control_output in security mode could be : max( last control output ; user defined output ) so that a minimal floor of heating is always applied when in security mode ? 

Regards,

**Comment by jmcollin78** [comment]
Ok i get you now. But imagine on summer, if your temperature is not working anymore, then the heater will be on 5% (let’s keep this value). I’m not sure it is what you want also. Because the way of working totally depends on temperature sensor it will be very difficult to find a suitable way to do without it.

**Comment by jmcollin78** [comment]
Anyway i will keep the idea and try to find something around this.

**Comment by adi90x** [comment]
Hello,

Maybe we can use an input sensor for the value.
And then the user could set the value or a simple automation to update the
value based on something else.
For example, use another sensor (like temperature expected in the next 5
days from meteofrance or another integration) to set the minimal heating to
0% or 5,10,etc

Regards,
Adrien

Le jeu. 9 févr. 2023, 06:57, Jean-Marc Collin ***@***.***> a
écrit :

**Comment by jmcollin78** [comment]
Hello,  this seems too much complicated and the main objective of the Versatile Thermostat is to avoid automation.
After reflexion I think your first proposal (have a minimal on_percent value) when last on_percent is > 0 and security mode is on + a notification is the better solution.
In summer, the last on_percent will be 0 or the thermostat is off so there is no problem.

If you agree with that I will try to implement this this week-end, this could be quickly faisable.

Regards,
JM

**Comment by adi90x** [comment]
Hello,

Yes sound good,
I would just say : have a defined minimal on_percent when last on_percent
is below a user defined value :)
So that even if you were with 0% on_percent, your heater can goes into a
safety mode that heat at least a minimun  I think that is what most of
heater do in order to make sure that we have a "fail safe" situation in
case of any issue on the probe ( in french "Hors-Gel")

Regards,

Le ven. 10 févr. 2023, 08:36, Jean-Marc Collin ***@***.***> a
écrit :

**Comment by jmcollin78** [comment]
> ... when last on_percentis below a user defined value :)


I think you mean: _when last on_percent is **above** a user defined value :)_

If on_percent is 0 the heater don't have to be on (the summer case explained above)

**Comment by adi90x** [comment]
Hello, 

No I am really thinking below, the case (that happen to me last week) is : 

- You are at home you set temperature to 18° 
- You leave your house and Away setting is now 14°  => on_percent became 0 
- Temp sensor become unavailable
- You end up with a freezing home as on_percent was 0 , last available temp was for example 16/17 ( decreasing ) when sensor became unavailable and if situation remain for a long time you may even have freezing issues on your house pipe :) 

That's why my idea was to have a defined on_percent when below a threshold . To make sure that what ever happen at least a bit of heating will be applied.

In fact it could be something like : 

If on_percent > security_min_on_percent  ( the one I add in the PR to repleace the hardcoded 0.75) => security_mode like today : not heating anymore
If on_percent < another_security_threshold  => security_mode with on_percent at user-defined value : freeze protection
In between , as it is right now so it will stay at the on_percent 
For each situation, adding notification ( or  way to easily grab the info ) seems super-important !

We can also put those threeshold/ user-defined value as input_number so that user can easily modified them base on scheduler or other parameters.

**Comment by jmcollin78** [comment]
In your case, there is no security risk: by a security risk, I mean, a risk of fire because the heater will always be "on" if temperature sensor don't work and on_percent was > a value.

The security feature is covering that very important risk and not the house the risk "the house is too cold because the temperature sensor is off". This is another use case which should be handled differently.

So I understand your last proposition which is going in the same way. But:
1. if case one (on_percent > security_min_on_percent), your house is going to be cold because no heater will be started, which is not what you want,
2. the summer case: if the temperature sensor goes off on summer, the thermostat will start the heater and that is not what we want.

Another point I see, I that there is may be four configuration parameters or input_number (security delay, security_min_on_percent, another_security_threshold , user-defined value : freeze protection), and this is too much complex. I really want to Keep It Simple and Smart (KISS principles). I don't like that because that will be very difficult to explain how this parameters works together and that will generate many questions and frustrations.

So what I propose is the following:
1. I keep the security_min_on_percent added on your PR. This mean that no security mode will be activated if on_percent < security_min_on_percent,
2. I add a parameter: security on_percent which the on_percent in security mode. Because security mode cannot be activated if on_percent is < security_min_on_percent, there is no risk to activate the heater in summer. This can set to 0 if the user don't want to have a small heating period in security mode.

This makes 3 parameters only for the security mode. It is many, but it is certainly needed for this important feature.

I understand this proposition **will not cover your case**: in your case, when the temperature sensor goes off, the on_percent was 0 so, the security mode will never be activated (this have been fixed by a previous issue), but:
1. you will have a notification which informs you that your sensor is off, so that you are able to deal with that event,
2. I image a normal heater is working like that. It will never starts itself if last measured temperature was sufficient,
3. this case should be rare: heating, no more heating because away, thermometer goes off for a long time,
4. some users have 2 or more thermometer in their critical room combined with a mean or max value template as input temperature sensor to avoid this case.

I hope this is clear (if not I suggest to switch in french and contact you directly because my English is not so strong to explain difficult cases).

**Comment by jmcollin78** [comment]
> Not 100% sure to understand the 2nd parameter you want to add, is it a minimal heating in security mode ? If yes then I can easily solve my issue by setting security_min_on_percent = 0 and putting whatever minimal heating I want !

Yes that's it. But in your case the thermostat will never go to the security mode because on_percent is 0.

**Comment by jmcollin78** [comment]
> maybe instead of input_number we can implement a service to update all those different parameters to the integration

Yes good point. It is very easy to do with home assistant. See     async def service_set_presence(self, presence):
 and service_set_preset_temperature:

if you want to implement it after I will implement the 2nd parameter it would be great (and I can help if needed).

**Comment by jmcollin78** [comment]
Yes I'm on it now.
