### ISSUE TITLE
More preset options

### ISSUE THREAD

**Issue by Patrick1610** [jmcollin78/versatile_thermostat#448]
**Consider the alternative to create a free discusssion before making a feature request**
Discussions forum is [here](https://github.com/jmcollin78/versatile_thermostat/discussions).
You should check that a discussion relative to the same issue have not been already answered in the forum.

Please also check in the [closed issues](https://github.com/jmcollin78/versatile_thermostat/issues) for a similar case.

I want to create the schedules I now have in scheduler with Vtherm, but I am missing a couple of presets. 
I would like to have Eco, Home and Comfort. This is because before 07:00 I would like the thermostat to be at 17.5 (Eco), during the day at 19 (Home) and in the evening at 20 (Comfort). After 21:00 it will go back to Eco. I am using frost for another purpose and it is not a nice name to use instead of Eco during the morning and evening. 

I would also like to have a different preset for Sleep, since I want to change the temperature when we go to sleep. It would be amazing if that could be the same as presence, and listen to another entity state to automatically determine sleep preset.

**Comment by Patrick1610** [comment]
Also, I would really like the option to have just one 'Away' preset appear when disabling presence detection. So I can manually set the room to 'Away' preset using a scheduler component with my own logic for home/away.

**Comment by jmcollin78** [comment]
Hello @Patrick1610 ,

> This is because before 07:00 I would like the thermostat to be at 17.5 (Eco), during the day at 19 (Home) and in the evening at 20 (Comfort). After 21:00 it will go back to Eco

Eco -> eco. Home -> Comfort and Comfort -> Boost. And that is it.

> I would also like to have a different preset for Sleep

What I do is to set Boost one hour before going to sleep and set Comfort when people are sleeping, so that the room is hot but in the night the temperature goes down.

In a more general manner, I will not add more preset because they are many and sufficient pour 95% of use. I cannot add always more and more presets as requested. You have to adapt with the existing.

> Also, I would really like the option to have just one 'Away' preset appear when disabling presence detection. So I can manually set the room to 'Away' preset using a scheduler component with my own logic for home/away.

Idem I will not change this. All the logic is to have an automatic Away option. What is your own logic and why does this logic not fit the existing VTherm logic ?
