### ISSUE TITLE
Set preset internal 

### ISSUE THREAD

**Issue by adi90x** [jmcollin78/versatile_thermostat#45]
Hello again, 

Testing and playing with the security mode, it seems that ``_async_set_preset_mode_internal`` is setting last_temp and last_external_temp to ``now``
https://github.com/jmcollin78/versatile_thermostat/blob/9fe307ba1e8c16a6252cedf15fbc4459a496a882/custom_components/versatile_thermostat/climate.py#L1051-L1053
Not really sure why we want to update the last_available_temp when we set a preset.
But it means that as soon as we switch to SECURITY PRESET we also set last_available_temp to ``now`` so when we start the next cycle ``check_security`` will always return true as we compare this ``fake now`` to ``now `` and we exit from the SECURITY preset. 

Regards,
Adrien

**Comment by jmcollin78** [comment]
Yes, this is to fix a "bug" which have been signaled here: https://forum.hacf.fr/t/nouveau-thermostat-type-proportionnel-avec-gestion-des-presets-portes-et-fenetres-detection-de-mouvement-gestion-de-presence-et-surconsommation/19160/286

we have to wait after a consigne change to switch to security mode for this case:
1. heater is off and temperature is stable -> no temperature change are send by thermometer,
2. switch preset which should turn on the heater -> this switch immediatly to security mode.

We have to wait a few after a temperature change to let the thermometer send new temperature. Because the heater turns on, the temperature should change. If not -> security mode.

**Comment by adi90x** [comment]
OK but then we have another issue , as we are not staying in security mode, as soon as we switch in security we refresh last_temp value so obvisouly at next cycle it restart heater.
My test was with a very low cycle timing to test my PR and my heater was just going into security mode ( I just remove battery of the thermometer ) , then restarting an heating cycle again and again .

**Comment by jmcollin78** [comment]
You are right. Don't know how I missed that. I will add a fix for this.

**Comment by jmcollin78** [comment]
The 2.2.0.beta1 should fix this and many others enhancements on security mode.

I will check in my real home that all seems correct. If you want to do so, you are welcome ;)

**Comment by adi90x** [comment]
Will update to 2.2.0 and test everything in my home
