### ISSUE TITLE
virtual-boost-mode (physical boost mode - for devices without boost-button)

### ISSUE THREAD

**Issue by snickers2k** [jmcollin78/versatile_thermostat#566]
Since Tado (and others) have no physical boost-button

Would be awesome to;

Set to 25°C (for tado - or higher for other thermostats) to trigger a boost-mode-automation, which turns the desired temperature back to the previos state after XY of minutes.

since nobody needs 25°C anyways for longer

**Comment by jmcollin78** [comment]
Hello, I think this have already been claimed but refused because there was no real need of this. See https://github.com/jmcollin78/versatile_thermostat/issues/59

By the way, it is very easy to implement with automation and timer in HA directly. I cannot add feature that are too much specific. I hope, you will understand this.
