### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by kadaan** [jmcollin78/versatile_thermostat#57]
## Version of the custom_component
2.3.0

## Configuration
None

## Describe the bug
When trying to add the integration it fails with this error: `Config flow could not be loaded: 400: Bad Request`
I have had an old version of this integration installed and had tried to use it.  I had removed the integration.  I then upgraded the component in HACS to 2.3.0 and when I try to install the integration it fails.

## Debug log
Nothing useful

```text

Add your logs here.

```

**Comment by jmcollin78** [comment]
Hello @kadaan ,

Thank you for your report. Because you are the only one reporting this issue, I guess there is something on your side which prevent the integration to load.

Is there something special in your environment haos ? Docker ? locale ? temperature units / metrics ?

Have you tried to remove the integration, reboot HA (to be sure all is clean) and then re-install ?

Can you put the integration in debug mode, try to restart the installation and send me the booting log until the message "Config flow could not be loaded: 400: Bad Request" ?

To put it into debug mode you have to add this line in your logger.yaml:

```

logs:
  custom_components.versatile_thermostat: debug
```

Please adapt to your configuration.

**Comment by kadaan** [comment]
HOAS: No
Units: Fahrenheit, pounds
Home Assistant is running in Docker

These are the only logs:
```
2023-03-01 09:08:36.388 DEBUG (MainThread) [custom_components.versatile_thermostat.config_flow] CTOR BaseConfigFlow infos: {}
```

Uninstall, restart, HACS install, and integration install result in the same error with the single log line as listed above.

**Comment by jmcollin78** [comment]
Strange. Very strange.

Can you check that you don't have any remaining configuration entries. This is in the file core.config_entries or core.entity_registry in your config repo of HA.

search for versatile_thermostat and remove the block if you find one. 

This look like this in my home:

```
{
        "entry_id": "dcb48e2a03dbc60b562ccafae0bc2bb6",
        "version": 1,
        "domain": "versatile_thermostat",
        "title": "Thermostat musique",
        "data": {
          "name": "Thermostat musique",
          "heater_entity_id": "switch.radiateur_musique",
          "temperature_sensor_entity_id": "sensor.temperature_musique",
          "cycle_min": 7,
          "proportional_function": "tpi",
          "proportional_bias": 0.25,
          "eco_temp": 15.0,
          "away_temp": 15.0,
          "boost_temp": 20.0,
          "comfort_temp": 19.0,
          "power_temp": 12.0,
          "window_delay": 30,
          "motion_delay": 30,
          "motion_preset": "comfort",
          "no_motion_preset": "eco",
          "power_sensor_entity_id": "sensor.total_puissance_instantanee",
          "max_power_sensor_entity_id": "input_number.chauffage_puissance_delestage",
          "device_power": 2.0,
          "external_temperature_sensor_entity_id": "sensor.meteo_beynes_temperature",
          "tpi_coefc": 0.6,
          "tpi_coeft": 0.04,
          "presence_sensor_entity_id": "binary_sensor.maison_occupee",
          "no_presence_preset": "away",
          "tpi_coef_int": 0.4,
          "tpi_coef_ext": 0.05,
          "eco_away_temp": 12.0,
          "boost_away_temp": 17.0,
          "comfort_away_temp": 16.0,
          "temp_min": 12.0,
          "temp_max": 25.0,
          "minimal_activation_delay": 10,
          "security_delay_min": 60
        },
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": null,
        "disabled_by": null
      },
```

**Comment by jmcollin78** [comment]
I will try with your config Fahrenheit, pounds to see if it related. I have added the fahrenheit support before last week.

**Comment by kadaan** [comment]
Cool, let me know!

**Comment by jmcollin78** [comment]
Hello, I test in my test env with your configuration:
![Capture d’écran 2023-03-03 à 17 53 51](https://user-images.githubusercontent.com/1712374/222779868-d92a1d3a-1b97-4c89-88d1-1251b0bca8ba.png)

And I can create new VersatileThermostat without trouble:
![Capture d’écran 2023-03-03 à 17 53 14](https://user-images.githubusercontent.com/1712374/222780022-3252a3e9-e71a-47d1-8b2d-7fc799ac84a1.png)

![Capture d’écran 2023-03-03 à 17 53 21](https://user-images.githubusercontent.com/1712374/222780070-e8035ec9-db79-48de-9004-91fcf89ad9cc.png)

The newly created thermostat have the right configuration:
![Capture d’écran 2023-03-03 à 17 55 12](https://user-images.githubusercontent.com/1712374/222780170-8d761a04-aaad-424f-87a5-88856fceb24a.png)

I cannot reproduce your issue. Very sorry for that.

May be you can send me some screenshot so that I will be able your process and maybe something will alert me.

**Comment by kadaan** [comment]
I added a log line before each block in the config flow and it fails to log anything after https://github.com/jmcollin78/versatile_thermostat/blob/6e40a152627fd78d7d1bd58e201a7d1226777d42/custom_components/versatile_thermostat/config_flow.py#L183

**Comment by kadaan** [comment]
This is the error:
```
2023-03-07 10:02:08.054 DEBUG (MainThread) [custom_components.versatile_thermostat.config_flow] 6: extra keys not allowed @ data['translation_key']
```

**Comment by jmcollin78** [comment]
Oh fine. I will have a look with this error.

**Comment by jmcollin78** [comment]
This Line is correct. Have you a recent Home assistant installation ? If not i Guess you should do an update

**Comment by kadaan** [comment]
Update of Home Assistant fixed it.  Thanks!
