### ISSUE TITLE
[Feature Request] - Add an auto-start/stop feature for over_climate VTherm

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#585]
As a `over_climate`  VTherm user,
I often need to turn off manually the VTherm (and so the device) when no device is needed due to correct temperature conditions,
So that, It will turn off the fan and save more energy.

To do that:
1. A new feature is added in the list of features,
3. An auto_start/stop detection level is added into the same page. 4 detection levels will be available:
- none: no auto-start/stop is allowed
- slow: auto-start/stop will be used if there is really no need of device soon,
- fast: auto-start/stop will be used as soon as the device is no more useful, 
- medium: the intermediate configuration.
5. Add an entity in the VTherm device of type select which enable to change the detection level. The user will be able to enable or disable the auto-start/stop feature from an automation or simply change the level of needed.

With this only two parameters and an entity it should be possible to:
1. avoid too much unwanted start/stop. We should avoid starting and stop after each regulation cycle,
2. avoid starting a device when you are not present for a long time. You don't want your AC device to turn on when you are on holidays I guess.

Warning: this feature can interact with the window detection which turn off the VTherm (depending on the configuration). The first detection condition (window detection or auto-start/stop) will take the lead and block the second eventual condition.

Detection algorithm:
We use the current_temperature, target_temperature and slope temperature calculation to evaluate the need to start or stop.

We calculate an accumulated_error over time like that: accumulated_error = accumulated_error + (target - current) * weight

where weight is the total seconds with the last measure divided by 2 min (so that if 2 two measure are spaced by 2 minutes the weight is one).

1. if enable aut-start/stop is off, stop here.
2. If VTherm is on and in heating mode, when error_accumulated is < -error_threshold -> turn off  and save hvac  mode,
3. If VTherm is on and in Cooling mode, when error_accumulated is > error_threshold -> turn off  and save hvac  mode,
4. If VTherm is off and saved hvac mode is Heating and current_temperature + slope x dt <= target_temperature then turn on and set havc mode to the saved hvac_mode,
6. If VTherm is off and saved hvac mode is Cooling and current_temperature + slope x dt >= target_temperature then turn on and set havc mode to the saved hvac_mode

error_threshold is set to respectively 10 (° * min) in slow, 5 in medium and 2 in fast.
dt is set to respectively 30 min in slow, 15 min in medium and 7 min in fast detection level.

current_temperature + slope x dt <= target_temperature means that in dt minute, we will probably need to heat (resp. cool)

Event:
When auto-start/stop is doing something, a new event is sent to inform what have been done. This can be catch for automation.

Preset change:
On a preset change, the algorithm describe above should be run to turn on or off the device.

**Comment by jmcollin78** [comment]
Feel free to add comment or suggestion to this feature request. And vote for it with a 👍 if you are interested.

**Comment by cyrildumas** [comment]
Hello Jean Marc,
I just installed beta 6 for test.
I will keep you posted 
Regards 
Cyril

**Comment by jmcollin78** [comment]
I 'm on the way to release.

**Comment by sltelitsyn** [comment]
Thank you very much! As soon as I’d have an opportunity, I’d test it.

**Comment by jmcollin78** [comment]
Let me known. I have it running for 3 days now and it is working fine.

**Comment by cyrildumas** [comment]
Same here, I had to adjust between fast slow and medium depending on the rooms but so far so good.

**Comment by antcodd** [comment]
Is there also a way to automatically toggle between heating and cooling mode? At some times of the year where I live there is need for cooling during the hottest part of the day and heating late at night. Usually it is sensible to be off in the middle, but it would be good to flip hvac_mode if too far out of the target temperature range in the opposite direction that would have caused turning had it been in that mode. I don't like the AC built in heat_cool mode as it tends to give up too early and end up at least a degree off target (plus leaving the AC on unnecessarily, which makes some moderate temperates too cold due to airflow)

With Sensibo I have a convoluted set of app climate react schedules that I'd like to come close to replicating with VTherm with more intelligent auto off behaviour. With the Sensibo app I keep having to add more and more scheduled off or temperature threshold off 1 hour times to avoid unhelpful cases in the boundaries between time periods (like unnecessarily getting stuck cooling when the outside temperature is rapidly dropping anyway).

Night time: target temperate 18, turn on heating if below 17, turn on cooling if above 22

Evening: target temperature 22, turn on heating  below 21, turn on cooling above 24. Heat loss through window frames makes 20 feel cold.

Day: Turn on heating below 18, cooling above 24. Heat gain from sun makes 20 acceptable if AC is not attempting cooling.

This effectively tries to maintain a target temperature of 22-24 during the day and 17-21 at night.

I could probably do the mode flipping with an automation but it would be nice to be built in to the auto-off feature.

**Comment by jmcollin78** [comment]
Hello @antcodd,

This could be an idea but will be used 2 times per years and only if your device is HEAT and COOL. So it is too rare to be a core feature for my opinion.
If you write an automation, you can post it into the discussions, maybe someone will be interested.

**Comment by rynchop** [comment]
Good morning,
Before discovering Versatile Thermostat, I had several automations that worked but by comparing the 2 approaches, I decided to migrate to Vtherm because it was more complete and centralized management. Really a great development.

I have been using Vterm since the end of winter.
My configuration:
Atlantic heat pump in the living room, indoor and outdoor Xiaomi temperature sensors.
Strong self-regulation and self-ventilation. I plan to control the electric radiators in the rooms in the fall.
At the end of winter and spring, the heating mode worked quite well with auto_start activated.
Since the hot period, in cold mode, I find that the settings are not aggressive enough. It's slow to cool, the setpoint could be lower by one degree for example, and auto_start would be ineffective. 
I have looked through the documentation several times but I have not found how to configure Vtherm to meet my expectations.
I tried expert mode for a while but without success, perhaps because my parameters were not relevant, or because having started with the UI interface we cannot have some expert mode parameters in the confugyration.ayml?
Thanks for your help.

`hvac_modes:
  - "off"
  - heat
  - cool
  - auto
  - dry
  - fan_only
min_temp: 7
max_temp: 35
target_temp_step: 0.1
fan_modes:
  - auto
  - low
  - medium
  - high
  - diffuse
preset_modes:
  - none
  - eco
  - comfort
  - boost
swing_modes:
  - vertical
  - horizontal
  - both
  - Vertical_1
  - Vertical_2
  - Vertical_3
  - Vertical_4
current_temperature: 26.1
temperature: 26.5
fan_mode: auto
hvac_action: cooling
preset_mode: comfort
swing_mode: vertical
is_on: true
hvac_mode: cool
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 7
eco_temp: 20
boost_temp: 24
comfort_temp: 22.3
frost_away_temp: 7
eco_away_temp: 18
boost_away_temp: 23
comfort_away_temp: 20
target_temperature_step: 0.1
ext_current_temperature: 26.3
ac_mode: true
saved_target_temp: 25
saved_preset_mode: comfort
saved_hvac_mode: cool
saved_preset_mod_central_modee: comfort
saved_hvac_mode_central_mode: null
last_temperature_datetime: "2025-07-06T13:20:32.716944+02:00"
last_ext_temperature_datetime: "2025-07-06T13:26:09.268720+02:00"
minimal_activation_delay_sec: 3
minimal_deactivation_delay_sec: 0
total_energy: 4.36
last_update_datetime: "2025-07-06T13:45:30.437205+02:00"
timezone: Europe/Paris
temperature_unit: °C
is_device_active: true
device_actives:
  - climate.ac_uty_b8d7af3eee6e
nb_device_actives: 1
ema_temp: 25.91
is_used_by_central_boiler: false
temperature_slope: 0.28
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
last_change_time_from_vtherm: "2025-07-06T12:48:49.580237+02:00"
presence_sensor_entity_id: binary_sensor.nous_2_presents
presence_state: "off"
is_presence_configured: true
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: unavailable
is_power_configured: false
device_power: 3
power_temp: null
current_power: null
current_max_power: null
mean_cycle_power: null
motion_sensor_entity_id: null
motion_state: unavailable
is_motion_configured: false
motion_delay_sec: 0
motion_off_delay_sec: 0
motion_preset: null
no_motion_preset: null
window_state: unavailable
window_auto_state: unavailable
window_action: window_turn_off
is_window_bypass: false
window_sensor_entity_id: null
window_delay_sec: null
window_off_delay_sec: null
is_window_configured: false
is_window_auto_configured: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
is_safety_configured: true
safety_state: "off"
safety_delay_min: 60
safety_min_on_percent: 0.5
safety_default_on_percent: 0.1
is_auto_start_stop_configured: true
auto_start_stop_enable: true
auto_start_stop_level: auto_start_stop_fast
auto_start_stop_dtmin: 7
auto_start_stop_accumulated_error: 2
auto_start_stop_accumulated_error_threshold: 2
auto_start_stop_last_switch_date: "2025-07-06T12:48:49.566628+02:00"
is_over_climate: true
start_hvac_action_date: "2025-07-06T12:48:50.919739+02:00"
underlying_entities:
  - climate.ac_uty_b8d7af3eee6e
is_regulated: true
regulated_target_temperature: 28.6
auto_regulation_mode: auto_regulation_strong
regulation_accumulated_error: 26.10903320312498
auto_fan_mode: auto_fan_high
current_auto_fan_mode: auto_fan_high
auto_activated_fan_mode: high
auto_deactivated_fan_mode: auto
auto_regulation_use_device_temp: false
follow_underlying_temp_change: false
friendly_name: Versatile_PAC
supported_features: 441`

![Image](https://github.com/user-attachments/assets/2981da01-7c93-4cb3-8951-b2d34d6aedd1)

`2025-07-06 13:39:30.435 INFO regulation calculation will be done
 
2025-07-06 13:39:30.435 INFO dtemp (0.1) is < 0.1 -> forget the regulation send
 
2025-07-06 13:41:30.436 INFO Calling ThermostatClimate._send_regulated_temperature force=False
 
2025-07-06 13:41:30.436 INFO regulation calculation will be done
 
2025-07-06 13:41:30.436 INFO dtemp (0.1) is < 0.1 -> forget the regulation send
 
2025-07-06 13:43:30.437 INFO Calling ThermostatClimate._send_regulated_temperature force=False
 
2025-07-06 13:43:30.437 INFO regulation calculation will be done
 
2025-07-06 13:43:30.437 INFO dtemp (0.1) is < 0.1 -> forget the regulation send
 
2025-07-06 13:45:30.438 INFO Calling ThermostatClimate._send_regulated_temperature force=False
 
2025-07-06 13:45:30.438 INFO regulation calculation will be done
 
2025-07-06 13:45:30.438 INFO Regulated temp have changed to 28.8. Resend it to underlyings
 
2025-07-06 13:45:30.438 INFO (MainThread) [custom_components.versatile_thermostat.underlyings] VersatileThermostat-Versatile_PAC-climate.ac_uty_b8d7af3eee6e - Set setpoint temperature to: 28.8
 
2025-07-06 13:45:54.482 INFO Underlying climate climate.ac_uty_b8d7af3eee6e have changed. new_hvac_mode is cool (vs cool), new_hvac_action=cooling (vs cooling), new_target_temp=29.0 (vs 26.5), new_fan_mode=auto (vs auto)
 
2025-07-06 13:47:30.441 INFO Calling ThermostatClimate._send_regulated_temperature force=False
 
2025-07-06 13:47:30.441 INFO regulation calculation will be done
 
2025-07-06 13:47:30.441 INFO dtemp (0.0) is < 0.1 -> forget the regulation send
 
2025-07-06 13:48:54.503 INFO Underlying climate climate.ac_uty_b8d7af3eee6e have changed. new_hvac_mode is cool (vs cool), new_hvac_action=cooling (vs cooling), new_target_temp=29.0 (vs 26.5), new_fan_mode=auto (vs auto)
 
2025-07-06 13:49:30.439 INFO Calling ThermostatClimate._send_regulated_temperature force=False
 
2025-07-06 13:49:30.439 INFO regulation calculation will be done
 
2025-07-06 13:49:30.439 INFO dtemp (0.0) is < 0.1 -> forget the regulation send
 
2025-07-06 13:51:30.440 INFO Calling ThermostatClimate._send_regulated_temperature force=False
 
2025-07-06 13:51:30.440 INFO regulation calculation will be done
 
2025-07-06 13:51:30.440 INFO dtemp (0.1) is < 0.1 -> forget the regulation send
 
2025-07-06 13:52:54.616 INFO Underlying climate climate.ac_uty_b8d7af3eee6e have changed. new_hvac_mode is cool (vs cool), new_hvac_action=cooling (vs cooling), new_target_temp=29.0 (vs 26.5), new_fan_mode=auto (vs auto)
 
2025-07-06 13:53:30.440 INFO Calling ThermostatClimate._send_regulated_temperature force=False
 
2025-07-06 13:53:30.440 INFO regulation calculation will be done
 
2025-07-06 13:53:30.441 INFO dtemp (0.1) is < 0.1 -> forget the regulation send`

**Comment by jmcollin78** [comment]
> Good morning, Before discovering Versatile Thermostat, I had several automations that worked but by comparing the 2 approaches, I decided to migrate to Vtherm because it was more complete and centralized management. Really a great development.
> 
> I have been using Vterm since the end of winter. My configuration: Atlantic heat pump in the living room, indoor and outdoor Xiaomi temperature sensors. Strong self-regulation and self-ventilation. I plan to control the electric radiators in the rooms in the fall. At the end of winter and spring, the heating mode worked quite well with auto_start activated. Since the hot period, in cold mode, I find that the settings are not aggressive enough. It's slow to cool, the setpoint could be lower by one degree for example, and auto_start would be ineffective. I have looked through the documentation several times but I have not found how to configure Vtherm to meet my expectations. I tried expert mode for a while but without success, perhaps because my parameters were not relevant, or because having started with the UI interface we cannot have some expert mode parameters in the confugyration.ayml? Thanks for your help.
> 
> `hvac_modes:
> 
> * "off"
> * heat
> * cool
> * auto
> * dry
> * fan_only
>   min_temp: 7
>   max_temp: 35
>   target_temp_step: 0.1
>   fan_modes:
> * auto
> * low
> * medium
> * high
> * diffuse
>   preset_modes:
> * none
> * eco
> * comfort
> * boost
>   swing_modes:
> * vertical
> * horizontal
> * both
> * Vertical_1
> * Vertical_2
> * Vertical_3
> * Vertical_4
>   current_temperature: 26.1
>   temperature: 26.5
>   fan_mode: auto
>   hvac_action: cooling
>   preset_mode: comfort
>   swing_mode: vertical
>   is_on: true
>   hvac_mode: cool
>   type: null
>   is_controlled_by_central_mode: true
>   last_central_mode: null
>   frost_temp: 7
>   eco_temp: 20
>   boost_temp: 24
>   comfort_temp: 22.3
>   frost_away_temp: 7
>   eco_away_temp: 18
>   boost_away_temp: 23
>   comfort_away_temp: 20
>   target_temperature_step: 0.1
>   ext_current_temperature: 26.3
>   ac_mode: true
>   saved_target_temp: 25
>   saved_preset_mode: comfort
>   saved_hvac_mode: cool
>   saved_preset_mod_central_modee: comfort
>   saved_hvac_mode_central_mode: null
>   last_temperature_datetime: "2025-07-06T13:20:32.716944+02:00"
>   last_ext_temperature_datetime: "2025-07-06T13:26:09.268720+02:00"
>   minimal_activation_delay_sec: 3
>   minimal_deactivation_delay_sec: 0
>   total_energy: 4.36
>   last_update_datetime: "2025-07-06T13:45:30.437205+02:00"
>   timezone: Europe/Paris
>   temperature_unit: °C
>   is_device_active: true
>   device_actives:
> * climate.ac_uty_b8d7af3eee6e
>   nb_device_actives: 1
>   ema_temp: 25.91
>   is_used_by_central_boiler: false
>   temperature_slope: 0.28
>   hvac_off_reason: null
>   max_on_percent: null
>   have_valve_regulation: false
>   last_change_time_from_vtherm: "2025-07-06T12:48:49.580237+02:00"
>   presence_sensor_entity_id: binary_sensor.nous_2_presents
>   presence_state: "off"
>   is_presence_configured: true
>   power_sensor_entity_id: null
>   max_power_sensor_entity_id: null
>   overpowering_state: unavailable
>   is_power_configured: false
>   device_power: 3
>   power_temp: null
>   current_power: null
>   current_max_power: null
>   mean_cycle_power: null
>   motion_sensor_entity_id: null
>   motion_state: unavailable
>   is_motion_configured: false
>   motion_delay_sec: 0
>   motion_off_delay_sec: 0
>   motion_preset: null
>   no_motion_preset: null
>   window_state: unavailable
>   window_auto_state: unavailable
>   window_action: window_turn_off
>   is_window_bypass: false
>   window_sensor_entity_id: null
>   window_delay_sec: null
>   window_off_delay_sec: null
>   is_window_configured: false
>   is_window_auto_configured: false
>   window_auto_open_threshold: null
>   window_auto_close_threshold: null
>   window_auto_max_duration: null
>   is_safety_configured: true
>   safety_state: "off"
>   safety_delay_min: 60
>   safety_min_on_percent: 0.5
>   safety_default_on_percent: 0.1
>   is_auto_start_stop_configured: true
>   auto_start_stop_enable: true
>   auto_start_stop_level: auto_start_stop_fast
>   auto_start_stop_dtmin: 7
>   auto_start_stop_accumulated_error: 2
>   auto_start_stop_accumulated_error_threshold: 2
>   auto_start_stop_last_switch_date: "2025-07-06T12:48:49.566628+02:00"
>   is_over_climate: true
>   start_hvac_action_date: "2025-07-06T12:48:50.919739+02:00"
>   underlying_entities:
> * climate.ac_uty_b8d7af3eee6e
>   is_regulated: true
>   regulated_target_temperature: 28.6
>   auto_regulation_mode: auto_regulation_strong
>   regulation_accumulated_error: 26.10903320312498
>   auto_fan_mode: auto_fan_high
>   current_auto_fan_mode: auto_fan_high
>   auto_activated_fan_mode: high
>   auto_deactivated_fan_mode: auto
>   auto_regulation_use_device_temp: false
>   follow_underlying_temp_change: false
>   friendly_name: Versatile_PAC
>   supported_features: 441`
> 
> ![Image](https://github.com/user-attachments/assets/2981da01-7c93-4cb3-8951-b2d34d6aedd1)
> 
> `2025-07-06 13:39:30.435 INFO regulation calculation will be done
> 
> 2025-07-06 13:39:30.435 INFO dtemp (0.1) is < 0.1 -> forget the regulation send
> 
> 2025-07-06 13:41:30.436 INFO Calling ThermostatClimate._send_regulated_temperature force=False
> 
> 2025-07-06 13:41:30.436 INFO regulation calculation will be done
> 
> 2025-07-06 13:41:30.436 INFO dtemp (0.1) is < 0.1 -> forget the regulation send
> 
> 2025-07-06 13:43:30.437 INFO Calling ThermostatClimate._send_regulated_temperature force=False
> 
> 2025-07-06 13:43:30.437 INFO regulation calculation will be done
> 
> 2025-07-06 13:43:30.437 INFO dtemp (0.1) is < 0.1 -> forget the regulation send
> 
> 2025-07-06 13:45:30.438 INFO Calling ThermostatClimate._send_regulated_temperature force=False
> 
> 2025-07-06 13:45:30.438 INFO regulation calculation will be done
> 
> 2025-07-06 13:45:30.438 INFO Regulated temp have changed to 28.8. Resend it to underlyings
> 
> 2025-07-06 13:45:30.438 INFO (MainThread) [custom_components.versatile_thermostat.underlyings] VersatileThermostat-Versatile_PAC-climate.ac_uty_b8d7af3eee6e - Set setpoint temperature to: 28.8
> 
> 2025-07-06 13:45:54.482 INFO Underlying climate climate.ac_uty_b8d7af3eee6e have changed. new_hvac_mode is cool (vs cool), new_hvac_action=cooling (vs cooling), new_target_temp=29.0 (vs 26.5), new_fan_mode=auto (vs auto)
> 
> 2025-07-06 13:47:30.441 INFO Calling ThermostatClimate._send_regulated_temperature force=False
> 
> 2025-07-06 13:47:30.441 INFO regulation calculation will be done
> 
> 2025-07-06 13:47:30.441 INFO dtemp (0.0) is < 0.1 -> forget the regulation send
> 
> 2025-07-06 13:48:54.503 INFO Underlying climate climate.ac_uty_b8d7af3eee6e have changed. new_hvac_mode is cool (vs cool), new_hvac_action=cooling (vs cooling), new_target_temp=29.0 (vs 26.5), new_fan_mode=auto (vs auto)
> 
> 2025-07-06 13:49:30.439 INFO Calling ThermostatClimate._send_regulated_temperature force=False
> 
> 2025-07-06 13:49:30.439 INFO regulation calculation will be done
> 
> 2025-07-06 13:49:30.439 INFO dtemp (0.0) is < 0.1 -> forget the regulation send
> 
> 2025-07-06 13:51:30.440 INFO Calling ThermostatClimate._send_regulated_temperature force=False
> 
> 2025-07-06 13:51:30.440 INFO regulation calculation will be done
> 
> 2025-07-06 13:51:30.440 INFO dtemp (0.1) is < 0.1 -> forget the regulation send
> 
> 2025-07-06 13:52:54.616 INFO Underlying climate climate.ac_uty_b8d7af3eee6e have changed. new_hvac_mode is cool (vs cool), new_hvac_action=cooling (vs cooling), new_target_temp=29.0 (vs 26.5), new_fan_mode=auto (vs auto)
> 
> 2025-07-06 13:53:30.440 INFO Calling ThermostatClimate._send_regulated_temperature force=False
> 
> 2025-07-06 13:53:30.440 INFO regulation calculation will be done
> 
> 2025-07-06 13:53:30.441 INFO dtemp (0.1) is < 0.1 -> forget the regulation send`

This issue is closed. You should rather post a new discussion.
