### ISSUE TITLE
Add Boost+1H preset

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#59]
This new preset aims to:
1. activate the heater with 100% power for one hour,
2. get back to the previous preset after the hour.

A service to activate this preset is needed (should be the default service).

No temperature feedback is needed during this hour.

This feature will be used, when a temporay boost is needed without the risk to forget the Boost mode. This could be interesting in that case (example):
1. you are outside (so Eco mode is selected) and want to go home,
2. you want to anticipate the heating of your house before you came in
3. so you have created an automation to 'boost+1H' your house waiting for your arrival.

**Comment by jmcollin78** [comment]
No real needs for this feature. Will not develop it.

**Comment by salabur** [comment]
If I´m not mistaken a boost a the beginning should be very useful to us with the TRV devices (warm water based central heating). Here the problem is that many (all my 6 devices) will compare the set temperature to the internal temperature sensor (even if set otherwise via mqtt) and in this way slow down the heating process, as the heating is stopped at the point where the temperature is reached at this point close to the heater and only resumes when the heat is spreading in the room and therefore the local temperature is low enough.

**Comment by jmcollin78** [comment]
In case of central heating, it is advisable to have a long cycle (15 min minimum) and a min power percent relatively high to avoid the case you are reporting.

I would recommend:

cycle_min: 15 (or more depending of your equipement -> in the first page of integration configuration),
minimal_activation_delay_sec: 300 (minium heating period will be 5 min -> in the last page of configuration)

May be you can try with those parameters to see if it solve the point.

What I understand is that your point is not related to this issue (add a Boost+1H preset).

**Comment by salabur** [comment]
I'll be happy to test your suggestion - thanks for that too.
