### ISSUE TITLE
Add support for damper controls

### ISSUE THREAD

**Issue by bytenik** [jmcollin78/versatile_thermostat#94]
Many sophisticated HVAC systems have electric controllable dampers to shut individual rooms on/off of the HVAC system. A proper controlling solution would allow setpoints/schedules/etc per room, and would be able to call for heat/AC/etc and then actuate dampers to heat or cool only the rooms that need it. Additionally, many multi-stage HVAC solutions would then also be better utilized by locking out stages when less rooms are operating.

For example, my home has dual stage geothermal cooling, and dual stage geothermal + single stage electric resistance + single stage propane (4 total stage) heating. But if only one room is being heated/cooled, it makes sense to never go beyond stage 1 cooling and stage 1 or 2 heating depending on the outside temperature.

I would be happy to collaborate on the development of functionality like this; I was planning on building it entirely myself in its own integration, but I would have ended up having to reproduce a lot of the work you've already accomplished!

**Comment by jmcollin78** [comment]
Hello @bytenik ,

If you decide to implement this, it will be glad to help. The algorithm is configurable so you can have a specific algorithm implementation.
By design the VTherm is able to control multiple heater in a same room (so with the same preset and temperature). Not sure if it is possible to address multiple room with one VTherm.
