### ISSUE TITLE
Use the real power measurement instead of the max_power 

### ISSUE THREAD

**Issue by Merangle** [jmcollin78/versatile_thermostat#96]
**Is your feature request related to a problem? Please describe.**
One question : 
Why do you use the max_power parameter in the power management instead of the real consumption of the header (if available) ? 
By doing so, you should avoid to unnecessary stop a heater. 

I assume that in each cycle, you compare the sum of max_power of all heaters to the max power available. But when the temperature is stabilized in your house, all heaters are not using the max-power but only a fraction of it. in this case the sum of all real consumptions is lower than the sum of all max-power and you do no need to activate the max-power function.

Just an idea !
Regards

**Comment by jmcollin78** [comment]
Hello @Merangle , this is because I don't have the real power consumed for one heater.
To do that I should integrate a new sensor per heater to get the power.
Second reason, for security it is better to take the max possible power of a device. This is the only way to be sure power will not be exceeded. Think about auto managed device that are able to activate themself with a variable power.

**Comment by Merangle** [comment]
Hello 
You say you don't have the real power consumed for one heater. 
What is measured in the current_power attribute ?

Do I understand right if the rule you use is the following :
if (Instant Power consumed + max-power of the heater that must be started ) > max-power authorized then you do no start the heater ? 

Thanks

**Comment by jmcollin78** [comment]
The current_power attribute is the power consuption of the home and not of the heater.
It is used by power management.

If current_power (of home) + max_power (of heater) > max_power (of home) -> we don't turn the heater on.

I have no sensor of the real power of each heater.
