### ISSUE TITLE
Switch not showing up during setup

### ISSUE THREAD

**Issue by darknessblade** [jmcollin78/versatile_thermostat#97]
-->

## Version of the custom_component
N/A

## Configuration
N/A

Add your logs here.
N/A
```

## Describe the bug
When setting up the integration the switch I want to use is not showing up in the list
The switch its sensor information does show up when selecting the thermostat

The switch I am using/planning to use:
aliexpress.com/item/1005005434987998.html?

I am using ZHA to setup/manage my zigbee devices


## Debug log
N/A

**Comment by darknessblade** [comment]
I think it has to do with the switch itself.

I get the occasional "Failed to call service light/turn_off. connection lost" error.

Soo the switch itself might be faulty

**Comment by jmcollin78** [comment]
light ? This is a switch configured as a light ?
Light are now visible by VTherm, only switch and input_boolean are.

**Comment by darknessblade** [comment]
Yeah I find that weird as well...

how would I need to set it up? [Do you have a template, so I have it configured correctly]

**Comment by jmcollin78** [comment]
There is no more template for configuring VTherm all is now done with the integration UI directly.
I think you can edit the entity light and set the device type to "switch" here (in French):

![Capture d’écran 2023-08-16 à 21 18 11](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/97823d25-4bd8-46b6-81a8-bbe9cef65a6c)

But this will not resolve your hardware problem (or radio issue ? I have to reconfigure my Zigbee channel because it was interfering with the Wifi to make it very stable).

See here: https://community.jeedom.com/t/informations-sur-cohabitation-zigbee-et-wifi/50821 (in French too)

**Comment by darknessblade** [comment]
Under the Entity information I cannot view/change the entity type

as for Wifi channels, after checking it with wifi-analysor, there are not many that interfere.
sadly everyone in my area has their wifi channel set to dynamic, so on day 1  C1-5 are not occupied, but on day 2 it could be occupied.

Will check first with another switch I plan to order. {can always use this one for something else.}

Still need 1-2 more temp sensors [1 put inside a waterproof case for a DIY outdoor one] and one as a additional failsafe for the room. [currently using 2 that are combined into 1 indoor sensor, taking the average room temp] [max difference is about 0.3C]

**Comment by jmcollin78** [comment]
I close this issue because it is not a VTherm problem. Don't hesitate to reopen if you think I' wrong or to continue this conversation on Discord (jm.collin).
